name: Deploy Documents

on:
  push:
    branches:
      - main
      - feat/init

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v3

      # 设置 Node.js 版本
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 安装 pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Docs
        run: pnpm build:docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DOC_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
